spring:
  profiles:
    active: ${APPLICATION_PROFILE}
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 10
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_EXTERNAL_PORT}
      password: ${REDIS_PASSWORD}
    web:
      pageable:
        one-indexed-parameters: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_EXTERNAL_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${MESSAGE_BROKER_HOST}
    port: ${MESSAGE_BROKER_EXTERNAL_PORT}
    username: ${MESSAGE_BROKER_USERNAME}
    password: ${MESSAGE_BROKER_PASSWORD}
  cloud:
    aws:
      s3:
        endpoint: ${AWS_S3_ENDPOINT}:${AWS_S3_EXTERNAL_PORT}
        region: ${AWS_S3_REGION}
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_KEY}
      region:
        static: ${AWS_S3_REGION}
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            enable: true
            trust: smtp.gmail.com
  thymeleaf:
    check-template-location: false

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

springdoc:
  api-docs:
    path: /api-docs

logbook:
  format:
    style: json
  strategy: default
  predicate:
    include:
      - path: /${SERVER_CONTEXT_PATH}/api/**
        methods:
          - GET
          - POST
          - PATCH
          - PUT
          - DELETE
      - path: /${SERVER_CONTEXT_PATH}/graphql
        methods:
          - POST
  filter:
    enabled: true
  obfuscate:
    headers:
      - Authorization
      - Cookie
    parameters:
      - password
      - accessToken
    json-body-fields:
      - password
      - accessToken
    replacement: XXXXXX
  write:
    level: TRACE
  max-body-size: 100000
  exclude:
    content-types:
      - application/octet-stream
  request:
    conditions:
      methods: [GET, POST, PUT, PATCH, DELETE]

logging:
  level:
    org:
      springframework:
        data: WARN
        batch: WARN
        security: WARN
        amqp: WARN
      hibernate: WARN
      zalando:
        logbook:
          Logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

application:
  default-admin:
    username: ${DEFAULT_ADMIN_USERNAME}
    password: ${DEFAULT_ADMIN_PASSWORD}
    email: ${DEFAULT_ADMIN_EMAIL}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRED}
    refresh-expiration: ${JWT_REFRESH_EXPIRED}

server:
  servlet:
    context-path: /${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}