scrape_configs:
  - job_name: 'prometheus-self'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:9090' ]

  - job_name: 'hexagonal-template-backend-metrics'
    metrics_path: '/hexagonal-template-backend/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Hexagonal architecture template application'